# Generated by Django 3.2.6 on 2022-06-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nisdac',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
