# Generated by Django 3.2.6 on 2022-06-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0002_patient_nisdac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='nisdac',
        ),
    ]
