# Generated by Django 3.2.6 on 2022-06-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0004_auto_20220613_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
    ]
