# Generated by Django 3.2.6 on 2022-06-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0006_auto_20220613_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
    ]
