# Generated by Django 3.2.6 on 2022-06-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0007_auto_20220613_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
