# Generated by Django 3.2.6 on 2022-06-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0014_alter_appointment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
    ]
