# Generated by Django 3.2.6 on 2022-06-13 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0015_remove_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='appsample.patient'),
            preserve_default=False,
        ),
    ]
