# Generated by Django 3.2.6 on 2022-06-14 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0019_auto_20220614_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinic_date',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appsample.clinicdate'),
        ),
    ]
