# Generated by Django 3.2.6 on 2022-06-14 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0020_alter_appointment_clinic_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsample.clinic'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='clinic_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsample.clinicdate'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_as_doctor', to='appsample.employee'),
        ),
    ]
