# Generated by Django 3.2.6 on 2022-06-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0021_auto_20220614_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'permissions': [('view_all', 'Can view all appointments')]},
        ),
    ]
