# Generated by Django 3.2.6 on 2022-06-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0023_alter_appointment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmentnumber',
            new_name='appo_no',
        ),
    ]
