# Generated by Django 3.2.6 on 2022-06-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0025_invoice_dsddsd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='dsddsd',
        ),
    ]
