# Generated by Django 3.2.6 on 2022-06-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0028_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
