# Generated by Django 3.2.6 on 2022-06-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0030_auto_20220616_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_by',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
