# Generated by Django 3.2.6 on 2022-06-15 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appsample', '0032_alter_news_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='News2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('readers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
