# Generated by Django 3.2.6 on 2022-06-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0033_news2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'permissions': []},
        ),
    ]
