# Generated by Django 3.2.6 on 2022-06-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0034_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'permissions': [('view_doctor', 'Can view doctors appointments')]},
        ),
    ]
