# Generated by Django 3.2.6 on 2022-06-16 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0035_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appoinment_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appsample.appoinmentstatus'),
        ),
    ]
