# Generated by Django 3.2.6 on 2022-06-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0036_alter_appointment_appoinment_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoiceservice',
            table='appsample_invoice_service',
        ),
    ]
