# Generated by Django 3.2.6 on 2022-06-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0037_alter_invoiceservice_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoiceservice',
            table='appsample_invoiceservice',
        ),
    ]
