# Generated by Django 3.2.6 on 2022-06-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0038_alter_invoiceservice_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
