# Generated by Django 3.2.6 on 2022-06-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0039_invoice_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total',
            new_name='discounted_total',
        ),
    ]
