# Generated by Django 3.2.6 on 2022-06-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsample', '0040_rename_total_invoice_discounted_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceservice',
            name='multiple',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
